### ISSUE TITLE
IDE can't resolve Element struct

### ISSUE THREAD

**Issue by tmkontra** [sandmor/ptable#1]
Hi sandmor, thanks for sharing this library! I'm using it as the data engine for https://github.com/ttymck/stoichkit

I was confused because Intellij IDEA can't resolve the `Element` class, and upon inspecting the source code, it looks like you are using an advanced build pipeline to keep the Element data in JSON and out of the source code. I see the Element `impl` but no `struct` block (v0.3.2).

I wanted to ask if you could help me understand how the library works, and possibly understand why Intellij might fail to index the `Element` member.

**Comment by sandmor** [comment]
Sorry for the late reply, I haven't used github in a long time (and I have email notifications disabled, I am going to activate them), I login to give a star to a repository and I noticed this notification, the pipeline is simple, the compiler(cargo) builds build.rs and run it, build.rs reads PubChemElements_all.json and parse it, then write a Rust file which is then included in the code with the line [https://github.com/sandmor/ptable/blob/master/src/lib.rs#L23](url). you can view the final file in [https://docs.rs/ptable/0.3.2/src/ptable/opt/rustwide/target/debug/build/ptable-46821f9969a8786a/out/data.rs.html#3-122](url), or opening docs.rs/ptable go to Element and click on src button. If you have any issues you are welcome to post them.

**Comment by tmkontra** [comment]
@sandmor no worries and thank you for taking the time to explain! Your explanation helped me find this issue
https://github.com/intellij-rust/intellij-rust/pull/4573 

It turns out the Rust plugin for Intellij requires you to activate the experimental feature to index generated code:
Find Action > Experimental Features > + (org.rust.cargo.fetch.out.dir, org.rust.cargo.evaluate.build.scripts)
